spring:
  application:
    name: pmv-service-test
  datasource:
    platform: h2
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8000

debug: true